### ISSUE TITLE
Benchmark generated html is empty

### ISSUE THREAD

**Issue by bhallionOhbibi** [Unity-Technologies/PerformanceBenchmarkReporter#1]
Hi !

I successfully generated a PerformanceBenchmark using the UnityPerformanceBenchmarkReporter.dll
But the result html is not showing any relevant data

input -> result.xml:
[results.xml](https://github.com/Unity-Technologies/PerformanceBenchmarkReporter/files/2420334/results.zip)

output -> UnityPerformanceBenchmark.html:
[UnityPerformanceBenchmark.html
![unityperformancebenchmarkpreview](https://user-images.githubusercontent.com/29798639/46089558-10cb5a00-c1af-11e8-8a53-b5a4bfe02816.png)
](https://github.com/Unity-Technologies/PerformanceBenchmarkReporter/files/2420332/UnityPerformanceBenchmark.zip)

**Comment by seanstolberg-unity** [comment]
Hello, I took a look at the result file you sent, and opened from the
2018.2 version of the Perf Benchmark Reporter. I do see FPS, object count,
triangles and vertices showing values. It looks like from your
configuration that you're running from a PC, which is able to rendering
high FPS with very low Camera.Render and Render.Mesh CPU times. I'm not
surprised that the values show 0 in this case. If you try with a much more
complex scene you should see CPU times start to register. Does that make
sense?

Sean

[image: image.png]

**Comment by bhallionOhbibi** [comment]
Hi,
thank you for your quick response.
I dont know if it makes much sense. In the case, every field are empty (event ObjectCount) almost looks like a render error from the html.
Have you tried opening the second zipfile I provided ? It contains the output of the reporter tool.
I also used the 2018.2 version of the Perf benchmark Reporter.
Perhaps, if you are able to see more consistents results with the same input the problem is elsewhere (browser, dotnet, os version...).

I generated the result.xml using this sample project unmodified https://github.com/Unity-Technologies/XRAutomatedTests/releases 

I used the PC running test results as I was unable to retrieve any results from the Android Running test
(see: https://forum.unity.com/threads/unity-test-runner-results-file-from-android-and-ios.527152/). This is another problem, but perhaps you know something about this too.

**Comment by sigr3s** [comment]
Hi Sean,
I'm having the same issue, values are written to the report HTML using comma decimals. It seems like  InvariantCulture is not being used when generating the HTML maybe?

**Comment by Arkano** [comment]
Same issue here. Manually editing the reported values so that they use dots instead of commas allows the chart to render correctly. Using non-English locale (spain)

**Comment by NoxMortem** [comment]
Same issue here: non-english locale German (DE_AT)
[GeneratedReport.zip](https://github.com/Unity-Technologies/PerformanceBenchmarkReporter/files/3694349/GeneratedReport.zip)

Test Cases:
```
using NUnit.Framework;
using Unity.PerformanceTesting;
using UnityEngine;
using UnityEngine.Profiling;

namespace Testing.Editor.Performance
{
	public class ForListIteration
	{
		[Test, Performance]
		public void Test()
		{
			Measure.Method(() =>
			               {
				               var array = new int[1000000];
				               for (var i = 0; i < array.Length; i++)
					               array[i] = (i * i + 1) / (i * i + 1) + i;
				               Debug.Log(array[array.Length - 1]);
			               })
			       .Definition(sampleUnit: SampleUnit.Microsecond)
			       .WarmupCount(10)
			       .MeasurementCount(10)
			       .IterationsPerMeasurement(5)
			       .GC()
			       .Definition(sampleUnit: SampleUnit.Microsecond)
			       .Run();
		}

		[Test, Performance, Version("1")]
		public void Measure_Empty()
		{
			var allocated = new SampleGroupDefinition("TotalAllocatedMemory", SampleUnit.Megabyte);
			var reserved  = new SampleGroupDefinition("TotalReservedMemory",  SampleUnit.Megabyte);
			Measure.Custom(allocated, Profiler.GetTotalAllocatedMemoryLong() / 1048576f);
			Measure.Custom(reserved,  Profiler.GetTotalReservedMemoryLong() / 1048576f);
		}
	}
}
```

Report Window:
![grafik](https://user-images.githubusercontent.com/6750572/66269285-1be7aa00-e847-11e9-967b-2798d3a6538a.png)

Result and BaseLine
[ResultAndBaseLine.zip](https://github.com/Unity-Technologies/PerformanceBenchmarkReporter/files/3694352/ResultAndBaseLine.zip)

Using the baseline shows the same issue
```
PS C:\Users\Kevin Streicher\Documents\repositories\visionary\Visionary\tools\UnityPerformanceTestReporter> dotnet.exe .\
UnityPerformanceBenchmarkReporter.dll --results="C:/Users/Kevin Streicher/AppData/LocalLow/VRVis/Visionary\TestResults.x
ml" --baseline="C:/Users/Kevin Streicher/AppData/LocalLow/VRVis/Visionary\BaseLine.xml"

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at UnityPerformanceBenchmarkReporter.ExtensionMethods.TruncToSigFig(Double d, UInt32 digits) in C:\PerformanceBenchmarkReporter-GitLab\UnityPerformanceBenchmarkReporter\ExtensionMethods.cs:line 28
   at UnityPerformanceBenchmarkReporter.PerformanceTestRunProcessor.DeterminePerformanceResult(SampleGroupResult sampleGroup, UInt32 sigFig) in C:\PerformanceBenchmarkReporter-GitLab\UnityPerformanceBenchmarkReporter\PerformanceTestRunProcessor.cs:line 160
   at UnityPerformanceBenchmarkReporter.PerformanceTestRunProcessor.UpdateTestResultsBasedOnBaselineResults(List`1 baselineTestResults, List`1 testResults, UInt32 sigfig) in C:\PerformanceBenchmarkReporter-GitLab\UnityPerformanceBenchmarkReporter\PerformanceTestRunProcessor.cs:line 76
   at UnityPerformanceBenchmarkReporter.PerformanceBenchmark.AddTestResults(TestResultXmlParser testResultXmlParser, List`1 testRunResults, List`1 testResults, List`1 baselineTestResults, HashSet`1 xmlDirectoryPaths, HashSet`1 xmlFileNamePaths, Boolean isBaseline) in C:\PerformanceBenchmarkReporter-GitLab\UnityPerformanceBenchmarkReporter\PerformanceBenchmark.cs:line 115
   at UnityPerformanceBenchmarkReporter.PerformanceBenchmark.AddBaselinePerformanceTestRunResults(TestResultXmlParser testResultXmlParser, List`1 baselinePerformanceTestRunResults, List`1 baselineTestResults) in C:\PerformanceBenchmarkReporter-GitLab\UnityPerformanceBenchmarkReporter\PerformanceBenchmark.cs:line 53
   at UnityPerformanceBenchmarkReporter.Program.Main(String[] args) in C:\PerformanceBenchmarkReporter-GitLab\UnityPerformanceBenchmarkReporter\Program.cs:line 42
```

While without baseline= option it generates, but is empty.

**Comment by seanstolberg-unity** [comment]
I have a fix on the way for this...

**Comment by seanstolberg-unity** [comment]
This has been fixed guys, please use master branch for all Unity releases.

**Comment by Trost123** [comment]
Had the same issue while having Ukrainian regional format set in Windows.
`Unhandled Exception: System.FormatException: Input string was not in a correct format.
`
When providing a baseline file as a parameter.

Changed to UK regional format and now it works fine. So I guess this fix didn't cover all regions.
Not a blocker for me though.
