### ISSUE TITLE
No xml produced when running benchmark reporter

### ISSUE THREAD

**Issue by LukeFireproof** [Unity-Technologies/PerformanceBenchmarkReporter#2]
I've tried running the benchmark reporter from the project directory using the slightly modified command

> D:/UnityInstallations/2018.2.10f1/editor/Unity.exe -runTests -batchmode -projectPath "" -testPlatform Android -buildTarget Android -playergraphicsapi=OpenGLES3 -mtRendering -scriptingbackend=mono -testResults D:/Slowdev/PerfTests/PerfBenchmark_Android_OpenGLES3_MtRendering_Mono.xml -logfile D:/Slowdev/PerfTests/PerfBenchmark_Android_OpenGLES3_MtRendering_Mono_UnityLog.txt

The tests run fine on the target device but no xml file is produced.

**Comment by LukeFireproof** [comment]
Found this to be a subnet issue and now works fine!

**Comment by seanstolberg-unity** [comment]
Great! Thank you.
