### ISSUE TITLE
Doesn't work in Unity 2019

### ISSUE THREAD

**Issue by patrickreece2** [Unity-Technologies/PerformanceBenchmarkReporter#3]
It would be great to fix this to work in 2019! Thank you.

**Comment by PicklesIIDX** [comment]
I'm starting some work on adjusting this so it can support the version 2.0.3 of the test runner. It doesn't support all functionality yet, and I'm not sure if I'll have the time to finish it, but it'll at least read your xmls!
https://github.com/PicklesIIDX/PerformanceBenchmarkReporter/tree/performance-testing-api-2.0.3

**Comment by lic1227** [comment]
Please Fix this Issue!

**Comment by seanstolberg-unity** [comment]
This has been fixed guys. Please use master for all Unity releases.
