### ISSUE TITLE
Wrong TestResults date

### ISSUE THREAD

**Issue by cabauman** [Unity-Technologies/PerformanceBenchmarkReporter#4]
First of all, thanks for the recent update to support 2019.3!

Unity: 2019.3.0f6
Test Framework: 1.1.14
Performance testing API: 2.0.9 preview
Performance Benchmark Reporter: 1.0.0

I'm trying it out and works great so far, except the TestResults date always show up as 1/19/1970 (the time is off too). Here's a TestResults.xml file with the results for one test (I changed the extension to txt because Github doesn't support uploading xml files): 
[TestResults.txt](https://github.com/Unity-Technologies/PerformanceBenchmarkReporter/files/4605288/TestResults.txt)

![WrongDate](https://user-images.githubusercontent.com/6819362/81493507-c7744380-92db-11ea-8e92-f84b91ff0d50.PNG)

When I generate a report for [a results file in the XRAutomatedTest repository](https://github.com/Unity-Technologies/XRAutomatedTests/blob/2019.3/PerformanceTests/BuiltIn-VR-Perf/Baselines/OculusQuest_BuiltInXR_BuiltInRP_MultiPass_OpenGLES3_Linear_IL2CPP_ARM64/Baseline.xml), the date displays correctly. I haven't been able to determine the difference yet, but I'll continue looking into it.

**Comment by seanstolberg-unity** [comment]
If I understand correctly:

1. The date is being displayed correctly using the baseline file in the XRAutomatedTest repo
2. But the date is NOT displayed correctly when using a result file from a newly run test with the latest performance testing extension? Is that correct?

If so, would you being to share one of those result files with me?

**Comment by cabauman** [comment]
That's correct.

The TestResults file from a newly run test with the latest performance testing extension is in the original post above. You should be able to change the extension back to xml for better formatting. I only changed it to txt because Github doesn't support uploading xml files.

**Comment by cabauman** [comment]
So it looks like the performance package sets the "Date" field in seconds not milliseconds.

Changing this

`                StartTime =
                    new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddMilliseconds(
                        runResults.StartTime),`

to

`                StartTime =
                    new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddSeconds(
                        runResults.StartTime),`

fixed the issue for me. Should I make a pull request, or do you guys want to take care of it?

**Comment by seanstolberg-unity** [comment]
Thanks, Colt! I see your PR, we can continue this there.

**Comment by gintautasss** [comment]
Hey Colt!

We have fixed this in performance testing package version 2.1.0-preview and updated BenchmarkReporter to use the appropriate type.

Could you verify that the issue has been resolved with latest package and reporter versions?

**Comment by cabauman** [comment]
Hello @gintautasss,

Works great! That reduces my PR to just converting the display date to local time. Thanks for your quick response to the issue.

**Comment by seanstolberg-unity** [comment]
I created a new release with this fix: https://github.com/Unity-Technologies/PerformanceBenchmarkReporter/releases/tag/1.0.1
